version: "3.9"

services:
  windapi:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./windapi:/windapi  # Ensure this matches the actual path where manage.py is located
      - ./windapi/staticfiles:/windapi/staticfiles # Correct the path if needed

    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py test --keepdb --noinput &&
             python manage.py load_sample_data &&
             python manage.py load_api_data &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=postgres
      - DB_PASS=postgres
      - LOG_LEVEL=DEBUG  # Enable debug logging
    depends_on:
    # Enures that the postgres container is up and running before attempting migrations
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgis/postgis:16-3.4
    volumes:
      - dev-db-data:/var/lib/postgresql/data
      - test-db-data:/var/lib/postgresql/test_data  # Optional for test database persistence

    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./windapi/staticfiles:/usr/share/nginx/html/static  # Nginx default location for static files
    depends_on:
      - windapi
    networks:
      - backend

volumes:
  dev-db-data:
  static-data:
  test-db-data:

networks:
  backend: