worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /static/ {
            alias /windapi/staticfiles/;
            try_files $uri $uri/ =404;
        }

        location / {
            proxy_pass http://windapi:8000;  # Make sure this points to your Django app
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
