# worker_processes auto;

# events {
#     worker_connections 1024;
# }

# http {
#     server {
#         listen 80;

#         location /static/ {
#             alias /windapi/staticfiles/;
#             try_files $uri $uri/ =404;
#         }

#         location / {
#             proxy_pass http://windapi:8000;  # Make sure this points to your Django app
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#         }
#     }
# }

# worker_processes auto;

# events {
#     worker_connections 1024;
# }

# http {
#     server {
#         listen 80;
#         server_name yourdomain.com;

#         location /static/ {
#             root /windapi;  # Correct the path to match where static files are stored
#         }

#         location / {
#             proxy_pass http://windapi:8000;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         }
# }

# }


# Main Nginx Configuration

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log  /var/log/nginx/access.log;

    # Add your server block here
    server {
        listen 80;
        server_name _;

        # Serve static files
        location /static/ {
            alias /usr/share/nginx/html/static/;  # Match the mounted path inside Nginx container
            try_files $uri $uri/ =404;  # Return 404 if file is not found
        }

        # Proxy pass for Django app
        location / {
            proxy_pass http://windapi:8000;  # Proxy requests to the Django app
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
