# Generated by Django 5.0 on 2024-11-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdata',
            options={'verbose_name': 'Map data', 'verbose_name_plural': 'Map data'},
        ),
        migrations.AlterModelOptions(
            name='mapdatasources',
            options={'verbose_name': 'Map data source', 'verbose_name_plural': 'Map data sources'},
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.mapdatasources'),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mapdatasources',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
