# Generated by Django 5.0 on 2024-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mapdata',
            constraint=models.UniqueConstraint(fields=('position', 'source', 'value'), name='unique_position_source_value'),
        ),
    ]
