# Generated by Django 5.0 on 2024-11-21 14:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_alter_mapdata_options_alter_mapdatasources_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mapdatasources',
            options={},
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_data', to='mapping.mapdatasources'),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapdatasources',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
