# Generated by Django 5.0 on 2025-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_mapdata_unique_position_source_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdata',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='x_osgb36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapdata',
            name='y_osgb36',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
