# Generated by Django 5.0 on 2024-11-22 09:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='Unique ID for the data collection station', max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Location of the station as latitude and longitude', srid=4326)),
                ('elevation', models.FloatField(blank=True, help_text='Elevation above sea level in meters', null=True)),
                ('data_source', models.CharField(help_text='Source of the data, e.g., NOAA', max_length=100)),
                ('frequency', models.CharField(help_text='Frequency of data collection, e.g., hourly, daily', max_length=20)),
                ('data_units', models.CharField(help_text='Units of measurement, e.g., m/s for wind speed', max_length=50)),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when metadata was recorded')),
                ('description', models.TextField(blank=True, help_text='Additional description of the dataset')),
            ],
            options={
                'verbose_name_plural': 'Wind Metadata',
            },
        ),
        migrations.CreateModel(
            name='WindAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('feasibility', 'Feasibility Assessment'), ('wind_resource', 'Wind Resource Assessment'), ('site_suitability', 'Site Suitability Assessment')], max_length=20)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326)),
                ('turbine_type', models.CharField(choices=[('turbine_model_a', 'Turbine Model A'), ('turbine_model_b', 'Turbine Model B')], max_length=20)),
                ('date', models.DateField()),
                ('assessment_notes', models.TextField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('corine', 'Corine'), ('lidar', 'LiDAR')], default='corine', help_text='Type of dataset (Corine or LiDAR)', max_length=20)),
                ('easting', models.FloatField(blank=True, help_text='Easting coordinate for Corine data', null=True)),
                ('northing', models.FloatField(blank=True, help_text='Northing coordinate for Corine data', null=True)),
                ('roughness_value', models.FloatField(blank=True, help_text='Roughness value for Corine data', null=True)),
                ('x', models.FloatField(blank=True, help_text='X coordinate for LiDAR data', null=True)),
                ('y', models.FloatField(blank=True, help_text='Y coordinate for LiDAR data', null=True)),
                ('delta_z', models.FloatField(blank=True, help_text='Delta Z (roughness) value for LiDAR data', null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_data', to='wind_assessments.windmetadata')),
            ],
            options={
                'verbose_name_plural': 'Real Data',
            },
        ),
    ]
