# Generated by Django 5.0 on 2024-11-07 12:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_assessments', '0004_auto_20240920_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='Unique ID for the data collection station', max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Location of the station as latitude and longitude', srid=4326)),
                ('elevation', models.FloatField(blank=True, help_text='Elevation above sea level in meters', null=True)),
                ('data_source', models.CharField(help_text='Source of the data, e.g., NOAA', max_length=100)),
                ('frequency', models.CharField(help_text='Frequency of data collection, e.g., hourly, daily', max_length=20)),
                ('data_units', models.CharField(help_text='Units of measurement, e.g., m/s for wind speed', max_length=50)),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when metadata was recorded')),
                ('description', models.TextField(blank=True, help_text='Additional description of the dataset')),
            ],
            options={
                'verbose_name_plural': 'Wind Metadata',
            },
        ),
        migrations.CreateModel(
            name='RealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic point for the data measurement', srid=4326)),
                ('roughness_value', models.FloatField(help_text='Roughness value at the specified location')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_data', to='wind_assessments.windmetadata')),
            ],
            options={
                'verbose_name_plural': 'Real Data',
            },
        ),
    ]
