# Generated by Django 5.0 on 2024-11-21 11:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wind_assessments', '0006_remove_realdata_location_realdata_dataset_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windassessment',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='windassessment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='windassessment',
            name='lon',
        ),
        migrations.AddField(
            model_name='windassessment',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326),
        ),
    ]
