openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/user/create/:
    post:
      operationId: user_create_create
      description: Create a new user in the system.
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/user/me/:
    get:
      operationId: user_me_retrieve
      description: Manage the authenticated user.
      tags:
      - user
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: user_me_update
      description: Manage the authenticated user.
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: user_me_partial_update
      description: Manage the authenticated user.
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/user/token/:
    post:
      operationId: user_token_create
      description: Create a new auth token for user.
      tags:
      - user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/wind_assessments/wind_assessment/:
    get:
      operationId: wind_assessments_wind_assessment_list
      description: List all wind assessments for the authenticated user.
      tags:
      - wind_assessments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WindAssessment'
          description: ''
  /api/wind_assessments/wind_assessment/{id}/:
    get:
      operationId: wind_assessments_wind_assessment_retrieve
      description: Retrieve or update a specific wind assessment.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - wind_assessments
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WindAssessment'
          description: ''
    put:
      operationId: wind_assessments_wind_assessment_update
      description: Retrieve or update a specific wind assessment.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - wind_assessments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WindAssessment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/WindAssessment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/WindAssessment'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WindAssessment'
          description: ''
    patch:
      operationId: wind_assessments_wind_assessment_partial_update
      description: Retrieve or update a specific wind assessment.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - wind_assessments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedWindAssessment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedWindAssessment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedWindAssessment'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WindAssessment'
          description: ''
  /api/wind_assessments/wind_assessment/create/:
    post:
      operationId: wind_assessments_wind_assessment_create_create
      tags:
      - wind_assessments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WindAssessment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/WindAssessment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/WindAssessment'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WindAssessment'
          description: ''
components:
  schemas:
    AuthToken:
      type: object
      description: Serializer for the user auth token.
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
      - email
      - password
    PatchedUser:
      type: object
      description: Serializer for the user object.
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          writeOnly: true
          maxLength: 128
          minLength: 5
        name:
          type: string
          maxLength: 255
    PatchedWindAssessment:
      type: object
      properties:
        user:
          type: string
          format: email
          readOnly: true
        customer_name:
          type: string
          maxLength: 255
        site_name:
          type: string
          maxLength: 255
        report_type:
          $ref: '#/components/schemas/ReportTypeEnum'
        lat:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,5})?$
        lon:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,5})?$
        location:
          type: string
          nullable: true
          maxLength: 255
        turbine_type:
          $ref: '#/components/schemas/TurbineTypeEnum'
        assessment_notes:
          type: string
          nullable: true
        report_url:
          type: string
          format: uri
          nullable: true
          maxLength: 500
        date:
          type: string
          format: date
    ReportTypeEnum:
      enum:
      - feasibility
      - wind_resource
      - site_suitability
      type: string
      description: |-
        * `feasibility` - Feasibility Assessment
        * `wind_resource` - Wind Resource Assessment
        * `site_suitability` - Site Suitability Assessment
    TurbineTypeEnum:
      enum:
      - turbine_model_a
      - turbine_model_b
      type: string
      description: |-
        * `turbine_model_a` - Turbine Model A
        * `turbine_model_b` - Turbine Model B
    User:
      type: object
      description: Serializer for the user object.
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          writeOnly: true
          maxLength: 128
          minLength: 5
        name:
          type: string
          maxLength: 255
      required:
      - email
      - name
      - password
    WindAssessment:
      type: object
      properties:
        user:
          type: string
          format: email
          readOnly: true
        customer_name:
          type: string
          maxLength: 255
        site_name:
          type: string
          maxLength: 255
        report_type:
          $ref: '#/components/schemas/ReportTypeEnum'
        lat:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,5})?$
        lon:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,5})?$
        location:
          type: string
          nullable: true
          maxLength: 255
        turbine_type:
          $ref: '#/components/schemas/TurbineTypeEnum'
        assessment_notes:
          type: string
          nullable: true
        report_url:
          type: string
          format: uri
          nullable: true
          maxLength: 500
        date:
          type: string
          format: date
      required:
      - customer_name
      - date
      - report_type
      - site_name
      - turbine_type
      - user
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
